spring:
  profiles: local

  h2:
    console:
      enabled: true
      path: /test_console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: soulchild
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG

book:
  search:
    kakao:
      url: https://dapi.kakao.com
    naver:
      url: https://openapi.naver.com